Small bug fixed
На моїй машині у рядках 32,62, 82,196 були помилки (Error CS1503	Argument 1: cannot convert from 'string' to 'char'   та
Error CS1503	Argument 2: cannot convert from 'System.StringSplitOptions' to 'char')
Пофіксив цю помилку.

Прибрав усі try{} except(){} конструкції. Чому? було легше відслідковувати помилки через дебаггер.